/**
 * Seira Lockfile Architecture (Seira.lock)
 *
 * Represents deterministic dependency resolution and integrity verification.
 * Uses SHA-256 checksums for source integrity.
 */

import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

export interface LockedPackage {
  readonly name: string;
  readonly version: string;
  readonly source: string; // e.g. "path:../shared" or "workspace"
  readonly checksum: string; // SHA-256 hex string
  readonly dependencies?: string[];
}

export interface SeiraLock {
  readonly version: number;
  readonly packages: LockedPackage[];
}

export class LockfileManager {
  /**
   * Generates or computes a deterministic SHA-256 checksum across all files in a package directory.
   */
  public generatePackageChecksum(pkgDir: string): string {
    return this.computePackageChecksum(pkgDir);
  }

  public computePackageChecksum(pkgDir: string): string {
    const hash = createHash('sha256');
    const files: string[] = [];

    const collectFiles = (dir: string) => {
      let entries: string[];
      try {
        entries = readdirSync(dir);
      } catch {
        return;
      }
      entries.sort();

      for (const entry of entries) {
        if (entry.startsWith('.') || entry === 'node_modules' || entry === 'target') continue;
        const full = join(dir, entry);
        const stat = statSync(full);
        if (stat.isDirectory()) {
          collectFiles(full);
        } else if (stat.isFile() && (entry.endsWith('.sr') || entry.endsWith('.sra') || entry === 'Seira.toml')) {
          files.push(full);
        }
      }
    };

    collectFiles(pkgDir);
    files.sort();

    for (const f of files) {
      const content = readFileSync(f);
      hash.update(f);
      hash.update(content);
    }

    return hash.digest('hex');
  }

  /**
   * Serializes the lockfile into canonical TOML format.
   */
  public serialize(lock: SeiraLock): string {
    let out = `# This file is automatically generated by Seira.\n`;
    out += `# It is not intended for manual editing.\n`;
    out += `version = ${lock.version}\n\n`;

    const sortedPackages = [...lock.packages].sort((a, b) => a.name.localeCompare(b.name));
    for (const pkg of sortedPackages) {
      out += `[[package]]\n`;
      out += `name = "${pkg.name}"\n`;
      out += `version = "${pkg.version}"\n`;
      out += `source = "${pkg.source}"\n`;
      out += `checksum = "${pkg.checksum}"\n`;
      if (pkg.dependencies && pkg.dependencies.length > 0) {
        const depsStr = pkg.dependencies.map((d) => `"${d}"`).join(', ');
        out += `dependencies = [${depsStr}]\n`;
      }
      out += `\n`;
    }

    return out;
  }

  /**
   * Writes the lockfile to disk at `pkgDir/Seira.lock` or directly at `lockFilePath`.
   */
  public writeLockfile(pkgDirOrFile: string, lock: SeiraLock): void {
    const lockPath = pkgDirOrFile.endsWith('Seira.lock') ? pkgDirOrFile : join(pkgDirOrFile, 'Seira.lock');
    writeFileSync(lockPath, this.serialize(lock), 'utf-8');
  }

  /**
   * Reads and parses a `Seira.lock` from disk if present.
   */
  public readLockfile(pkgDirOrFile: string): SeiraLock | null {
    const lockPath = pkgDirOrFile.endsWith('Seira.lock') ? pkgDirOrFile : join(pkgDirOrFile, 'Seira.lock');
    if (!existsSync(lockPath)) return null;

    try {
      const content = readFileSync(lockPath, 'utf-8');
      return this.parse(content);
    } catch {
      return null;
    }
  }

  public parse(content: string): SeiraLock {
    const packages: LockedPackage[] = [];
    const lines = content.split(/\r?\n/);
    let currentPkg: Partial<LockedPackage> = {};
    let inPkg = false;

    for (let line of lines) {
      line = line.trim();
      if (!line || line.startsWith('#')) continue;

      if (line === '[[package]]') {
        if (inPkg && currentPkg.name && currentPkg.version) {
          packages.push(currentPkg as LockedPackage);
        }
        currentPkg = {};
        inPkg = true;
        continue;
      }

      const eqIdx = line.indexOf('=');
      if (eqIdx !== -1 && inPkg) {
        const key = line.slice(0, eqIdx).trim();
        const val = line.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');

        if (key === 'name') currentPkg = { ...currentPkg, name: val };
        else if (key === 'version') currentPkg = { ...currentPkg, version: val };
        else if (key === 'source') currentPkg = { ...currentPkg, source: val };
        else if (key === 'checksum') currentPkg = { ...currentPkg, checksum: val };
      }
    }

    if (inPkg && currentPkg.name && currentPkg.version) {
      packages.push(currentPkg as LockedPackage);
    }

    return {
      version: 1,
      packages,
    };
  }
}
